name: Auto Commit

on:
  schedule:
    - cron: '0 * * * *' # every hour
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create empty commit
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git commit --allow-empty -m "chore: hourly empty commit"
          git push
