name: Keep Streamlit Awake

on:
  schedule:
    - cron: '0 */2 * * *'  # every 2 hours
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make empty commit
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"
          git commit --allow-empty -m "Keep Streamlit awake"
          git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }}
          git push origin HEAD
