name: Keep Streamlit Awake

on:
  schedule:
    - cron: '0 */4 * * *'  # Every 4 hours (UTC)
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Make empty commit
        run: |
          git commit --allow-empty -m "Keep Streamlit awake"
          git push https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }} HEAD:main
